export const games = [
  {
    title: 'Arkanoid',
    slug: 'arkanoid',
    img: 'https://i.imgur.com/zclQt4C.png',
    backgroundColor: '#a41717',
    borderColor: '#e42020',
    shadowColor: '#b81e1e',
  },
  {
    title: 'Donkey Kong',
    slug: 'donkey-kong',
    img: 'https://i.imgur.com/1igRXn3.png',
    backgroundColor: '#ffb850',
    borderColor: '#c54e00',
    shadowColor: '#941c00',
  },
  {
    title: 'Pong',
    slug: 'pong',
    img: 'https://i.imgur.com/gkShWGs.png',
    backgroundColor: '#000000',
    borderColor: '#f6e01c',
    shadowColor: '#c9b818',
  },
  {
    title: 'Pacman',
    slug: 'pacman',
    img: 'https://i.imgur.com/oKJqvYf.png',
    backgroundColor: '#edd94f',
    borderColor: '#472c09',
    shadowColor: '#271805',
  },
  {
    title: 'Frogger',
    slug: 'frogger',
    img: 'https://i.imgur.com/PL8iIMV.png',
    backgroundColor: '#1f3311',
    borderColor: '#7bca40',
    shadowColor: '#6baf30',
  },
  {
    title: 'Space Invaders',
    slug: 'space-invaders',
    img: 'https://i.imgur.com/LgpzNFn.png',
    backgroundColor: '#0361ff',
    borderColor: '#6ba9ff',
    shadowColor: '#5a8fd9',
  },
  {
    title: 'Tetris',
    slug: 'tetris',
    img: 'https://i.imgur.com/t1RbvC0.png',
    backgroundColor: '#29b8e8',
    borderColor: '#004d96',
    shadowColor: '#003970',
  },
  {
    title: 'Galaga',
    slug: 'galaga',
    img: 'https://i.imgur.com/5V3uRbF.png',
    backgroundColor: '#5c0048',
    borderColor: '#a07099',
    shadowColor: '#835c7e',
  },
  {
    title: 'Centipede',
    slug: 'centipede',
    img: 'https://i.imgur.com/101qRBj.png',
    backgroundColor: '#433b70',
    borderColor: '#ff6666',
    shadowColor: '#cd3434',
  },
];
